name: Deploy nonproduction

on:
  push:
    branches:
      - feature*
      
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      BUCKET_NAME: cfst-3457-290e49cbc0f551444a5f1a5b3-nonprodbucket-1cquqejls61qi
    steps:
      - name: Check out code
        uses: actions/checkout@v2    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with: 
          node-version: 14
      - name: Build Site
        run: |
          npm ci
          npm run build
      - name: Deploy files to s3
        run: aws s3 cp ${{ env.BUCKET_NAME }}/ --recursive --acl public-read
        
